server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/meubanco
    username: eduardo
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: change_this_to_a_secure_random_string
    expiration-ms: 3600000
